# Generated by Django 2.2.2 on 2019-10-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('slug', models.SlugField(max_length=75)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('anchor', models.CharField(max_length=75)),
                ('slug', models.SlugField(max_length=75)),
                ('link', models.CharField(blank=True, max_length=1064)),
                ('app', models.CharField(blank=True, help_text='The App this is Connected To', max_length=150)),
                ('action', models.CharField(blank=True, help_text='The action this is connected to within the app', max_length=150)),
                ('params', models.TextField(blank=True, help_text='Additional params to allow processing')),
                ('icon', models.CharField(blank=True, max_length=35)),
                ('position', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='swish.Menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swish.MenuItem')),
            ],
        ),
    ]
