# Generated by Django 2.2.2 on 2019-10-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swish', '0003_component_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='linked_model',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
