# Generated by Django 2.2.6 on 2019-10-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name of extension.', max_length=100)),
                ('type', models.CharField(help_text='Extension Type', max_length=20)),
                ('element', models.CharField(help_text='Unique name of the element.', max_length=100)),
                ('path', models.CharField(help_text='Module Installed Path', max_length=150)),
                ('params', models.TextField(blank=True)),
                ('data', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('state', models.IntegerField()),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=35)),
                ('order', models.IntegerField(default=0)),
                ('block', models.ForeignKey(on_delete='cascade', to='draft.Block')),
                ('menuitem', models.ManyToManyField(to='draft.MenuItem')),
            ],
        ),
    ]
